# the public base url for your webhooks
publicHostname = "https://websub.example.com"

# a token used for feed subscriptions
verifyToken = "dILVKUkteZ5nG7U6BVhT8BZWfabaK77BDK0aev4ldt0CvCLuxS5K7qGQGjiQ5YH7"

[store]
# one of: "memory", "redis"
kind = "memory"

# defaults for redis:
addr = ""
password = ""
db = 0

[listener.listener_a]
# one of: "websub"
handler = "websub"

# the websub hub host
hubUrl = "https://pubsubhubbub.appspot.com/subscribe"
# the topic url you're subscribing to
topicUrl = "https://www.youtube.com/xml/feeds/videos.xml?channel_id=CHANNEL_ID"


[listener.listener_b]
handler = "websub"

hubUrl = "https://pubsubhubbub.appspot.com/subscribe"
topicUrl = "https://www.youtube.com/xml/feeds/videos.xml?channel_id=CHANNEL_ID_2"

[emitter.emitter_a]
# one of: "slack"
handler = "slack"
# make an app, add that app to your slack, then generate an incoming webhook
incomingWebhook = "https://hooks.slack.comm/services/.../.../..."

[emitter.emitter_b]
handler = "slack"
incomingWebhook = "https://hooks.slack.comm/services/.../.../..."


[wires]
# connect the dots
listener_a = ["emitter_a"]
listener_b = ["emitter_a", "emitter_b"]